name: Daily News Update
on:
  schedule:
    - cron: '0 7 * * *'  # Runs at 7 AM UTC every day
  workflow_dispatch:  # Allows manual trigger for testing

jobs:
  update-news:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'
      
      - name: Install dependencies
        run: |
          pip install requests beautifulsoup4 pandas openpyxl pytz
      
      - name: Run news generator
        env:
          CLAUDE_API_KEY: ${{ secrets.CLAUDE_API_KEY }}
        run: python tennews_generator.py
      
      - name: Commit and push if changed
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add public/news_data.json news_archive.xlsx
          git diff --quiet && git diff --staged --quiet || git commit -m "Update news - $(date +'%Y-%m-%d')"
          git push
